// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/24/2026, 5:47:19 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/projects/loveable-dwamee/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/projects/loveable-dwamee/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/projects/loveable-dwamee/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/projects/loveable-dwamee/plugins/**/*.{js,ts,mjs}","D:/projects/loveable-dwamee/composables/**/*.{js,ts,mjs}","D:/projects/loveable-dwamee/utils/**/*.{js,ts,mjs}","D:/projects/loveable-dwamee/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/projects/loveable-dwamee/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/projects/loveable-dwamee/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/projects/loveable-dwamee/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;